package docs

// This file is a placeholder for Swagger documentation.
// Actual documentation will be generated by Swaggo during Docker build
// If you want to generate the documentation manually, run:
// swag init --parseDependency --parseInternal -g cmd/main.go --output ./docs