services:
  db:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - /etc/healthy-summer/secrets/db.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    env_file:
      - /etc/healthy-summer/secrets/user-service.env
    ports:
      - "8084:8084"
    depends_on:
      - db
    volumes:
      - /etc/healthy-summer/secrets/user-service.env:/etc/healthy-summer/secrets/user-service.env:ro

  activity-service:
    build: ./activity-service
    container_name: activity-service
    restart: always
    env_file:
      - /etc/healthy-summer/secrets/activity-service.env
    ports:
      - "8081:8081"
    depends_on:
      - db
    volumes:
    - /etc/healthy-summer/secrets/activity-service.env:/etc/healthy-summer/secrets/activity-service.env:ro

  nutrition-service:
    build: ./nutrition-service
    container_name: nutrition-service
    restart: always
    env_file:
      - /etc/healthy-summer/secrets/nutrition-service.env
    ports:
      - "8082:8082"
    depends_on:
      - db
    volumes:
      - /etc/healthy-summer/secrets/nutrition-service.env:/etc/healthy-summer/secrets/nutrition-service.env:ro

  social-service:
    build: ./social-service
    container_name: social-service
    restart: always
    env_file:
      - /etc/healthy-summer/secrets/social-service.env
    ports:
      - "8083:8083"
    depends_on:
      - db
    volumes:
      - /etc/healthy-summer/secrets/social-service.env:/etc/healthy-summer/secrets/social-service.env:ro

volumes:
  pgdata: