services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: summer
      POSTGRES_PASSWORD: summer123
      POSTGRES_DB: healthy_summer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  user-service:
    build: ./user-service
    container_name: user-service
    env_file:
      - ./user-service/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  activity-service:
    build: ./activity-service
    container_name: activity-service
    env_file:
      - ./activity-service/.env
    depends_on:
      - db

  nutrition-service:
    build: ./nutrition-service
    container_name: nutrition-service
    env_file:
      - ./nutrition-service/.env
    depends_on:
      - db

  social-service:
    build: ./social-service
    container_name: social-service
    env_file:
      - ./social-service/.env
    depends_on:
      - db

volumes:
  pgdata: