// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/activities": {
            "post": {
                "description": "Create a new activity entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Post Activity",
                "parameters": [
                    {
                        "description": "Activity data",
                        "name": "activity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PostActivityRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Activity"
                        }
                    }
                }
            }
        },
        "/api/activities/{user_id}": {
            "get": {
                "description": "Get all activities for a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Get Activities",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Activity"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Activity": {
            "type": "object",
            "properties": {
                "calories": {
                    "type": "integer"
                },
                "duration_min": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "intensity": {
                    "$ref": "#/definitions/model.Intensity"
                },
                "location": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.Intensity": {
            "type": "string",
            "enum": [
                "low",
                "medium",
                "high"
            ],
            "x-enum-varnames": [
                "IntensityLow",
                "IntensityMedium",
                "IntensityHigh"
            ]
        },
        "model.PostActivityRequest": {
            "type": "object",
            "required": [
                "calories",
                "duration_min",
                "intensity",
                "timestamp",
                "type",
                "user_id"
            ],
            "properties": {
                "calories": {
                    "type": "integer"
                },
                "duration_min": {
                    "type": "integer"
                },
                "intensity": {
                    "$ref": "#/definitions/model.Intensity"
                },
                "location": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
